//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoSharing.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int ID { get; set; }
        public int PostID { get; set; }
        public string UserID { get; set; }
        public string Text { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ClientProfiles ClientProfiles { get; set; }
        public virtual Posts Posts { get; set; }
    }
}
