//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoSharing.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VideoSharingEntities1 : DbContext
    {
        public VideoSharingEntities1()
            : base("name=VideoSharingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationUsers> ApplicationUsers { get; set; }
        public virtual DbSet<ClientProfiles> ClientProfiles { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<ExceptionDescriptions> ExceptionDescriptions { get; set; }
        public virtual DbSet<IdentityRoles> IdentityRoles { get; set; }
        public virtual DbSet<IdentityUserClaims> IdentityUserClaims { get; set; }
        public virtual DbSet<IdentityUserLogins> IdentityUserLogins { get; set; }
        public virtual DbSet<IdentityUserRoles> IdentityUserRoles { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
    }
}
